spring.application.name=HairSalonProject2
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.thymeleaf.cache=false

spring.profiles.active=local
spring.profiles.include=secret

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
spring.mvc.hiddenmethod.filter.enabled=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

file.max-size=10485760
file.image.max-size=5242880

server.port=8080

kakao.rest-api-key=d55a2aa96b9f2478b354241a62eb0a48
